### PR TITLE
feat: adding auto-merge

### PR DESCRIPTION
**Pull request by IuryGama**

### CODE REVIEW

**Review by yann510 — APPROVED** [review]
Nice work Lury, thanks for the contribution! :rocket:

**Comment by yann510** [comment]
@IuryGama I've tried automatically merging the PR, but got this error:
image


Any ideas as to what the problem can be?

**Comment by IuryGama** [comment]
Hey @yann510, I found this: https://github.community/t/github-action-resource-not-accessible-by-integration/16034

It seems " OAuth tokens and GitHub Apps are restricted from editing the main.workflow file. This means it isn’t possible to merge a Pull Request via an Action if it updates the main.workflow file I’m afraid"

**Comment by yann510** [comment]
Thanks for the reply.
If I understand correctly, PRs cannot be merged as soon as a file is modified in the `.github` folder?

**Comment by IuryGama** [comment]
That's right @yann510. 
If others PRs fails, please let me know.

**Comment by yann510** [comment]
@IuryGama Awesome, I will try it out on another PR very soon :clap:

**Pull request merged**
